import {readFile} from 'node:fs/promises';import path from 'node:path';import {z} from 'zod';import type{PrismaClient}from'@prisma/client';import{buildRoadmap,type RoadmapDefinition}from'../domain/roadmap.js';
const schema=z.object({version:z.number(),chapters:z.array(z.object({id:z.number(),title:z.string(),subtitle:z.string(),gate:z.array(z.string())})),topics:z.array(z.object({id:z.string(),chapter:z.number(),order:z.number(),scenario:z.string(),question:z.string(),choices:z.array(z.string()).min(2),reveal:z.string(),uses:z.array(z.string()),signals:z.array(z.string()),problems:z.array(z.number()).min(3)}))});
const promptSchema=z.object({id:z.string(),kind:z.enum(['SHORT_TEXT','EXPLANATION','PREDICTION','CHOICE']),prompt:z.string(),modelAnswer:z.string(),rubric:z.array(z.string()).min(1),visualization:z.string().optional()});
const storySchema=z.record(z.object({expeditionTitle:z.string(),artifact:z.string(),mystery:z.string(),history:z.string(),stakes:z.string(),memoryAnchor:z.string(),expedition:z.array(z.string()).min(3),presencePrompts:z.array(promptSchema).min(1).optional(),source:z.object({label:z.string(),url:z.string().url()})}));
export async function loadRoadmap(){const root=process.env.LEARNING_ROOT??'../../learning';const raw=await readFile(path.resolve(root,'curriculum/roadmap.json'),'utf8');return schema.parse(JSON.parse(raw)) as RoadmapDefinition;}
export async function loadStories(){
  const root=process.env.LEARNING_ROOT??'../../learning';const raw=await readFile(path.resolve(root,'curriculum/topic-stories.json'),'utf8');const stories=storySchema.parse(JSON.parse(raw));
  return Object.fromEntries(Object.entries(stories).map(([id,story])=>[id,{...story,presencePrompts:story.presencePrompts??story.expedition.map((task,index)=>({id:`${id}-${index+1}`,kind:index===0?'PREDICTION':index===1?'EXPLANATION':'SHORT_TEXT',prompt:task,modelAnswer:`Uma resposta sólida precisa ligar esta investigação à ideia central de ${story.artifact.toLowerCase()}: ${story.memoryAnchor}`,rubric:['nomeia a regra ou representação relevante','explica a consequência para uma operação ou algoritmo','usa um exemplo, invariante ou limite para justificar'],visualization:id}))}]));
}
export async function roadmap(prisma:PrismaClient){
  const [definition,stories]=await Promise.all([loadRoadmap(),loadStories()]);const since=new Date(Date.now()-7*86400000);
  // Cast isolates a stale generated client during local TypeScript-only checks; Docker generates from this schema before serving.
  const competencies:any[]=await (prisma as any).competency.findMany({include:{snapshots:{orderBy:{createdAt:'desc'},take:1},challenges:{include:{attempts:{where:{outcome:'SUCCESS',usedHint:false},take:1}}},studySessions:{where:{startedAt:{gte:since}},take:1},explorations:{include:{responses:true},take:1}}});
  const evidence=Object.fromEntries(competencies.map(c=>[c.id,{name:c.name,score:c.snapshots[0]?.score??0,diagnosticPassed:c.challenges.some((ch:any)=>ch.id.startsWith('diagnostic-')&&ch.attempts.length>0),studiedRecently:c.studySessions.length>0,explored:c.explorations[0]?.completedAt!=null}]));
  const prerequisites=Object.fromEntries(competencies.map(c=>[c.id,c.prerequisites]));const built=buildRoadmap(definition,evidence,prerequisites);const enrich=<T extends{id:string}>(node:T|undefined)=>node?{...node,story:stories[node.id]}:undefined;
  const explorationById=Object.fromEntries(competencies.map(c=>[c.id,c.explorations[0]??null]));
  const decorate=<T extends{id:string}>(node:T|undefined)=>node?{...enrich(node)!,exploration:explorationById[node.id]}:undefined;
  return {...built,chapters:built.chapters.map(chapter=>({...chapter,nodes:chapter.nodes.map(node=>decorate(node)!)})),recommended:decorate(built.recommended),recommendedExplore:decorate(built.recommendedExplore),recommendedReinforce:decorate(built.recommendedReinforce),weakest:built.weakest.map(node=>decorate(node)!),randomPool:built.randomPool.map(node=>decorate(node)!)};
}
